{ self }:
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.zeroclaw;
  cfgFile = "${config.xdg.configHome}/zeroclaw/config.toml";
in
{
  options.services.zeroclaw = {
    enable = mkEnableOption "ZeroClaw AI assistant";

    package = mkOption {
      type = types.package;
      default = self.packages.${pkgs.system}.default;
      defaultText = literalExpression "inputs.zeroclaw.packages.\${pkgs.system}.default";
      description = "The ZeroClaw package to use.";
    };

    # API Configuration
    apiKey = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "API key for the provider. Consider using apiKeyFile instead for security.";
    };

    apiKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to a file containing the API key. Takes precedence over apiKey.";
    };

    provider = mkOption {
      type = types.str;
      default = "openrouter";
      description = "Default AI provider (openrouter, openai, anthropic, ollama, etc.).";
    };

    model = mkOption {
      type = types.str;
      default = "anthropic/claude-sonnet-4-20250514";
      description = "Default model to use.";
    };

    temperature = mkOption {
      type = types.float;
      default = 0.7;
      description = "Default temperature for responses.";
    };

    # Memory Configuration
    memory = {
      backend = mkOption {
        type = types.enum [ "sqlite" "markdown" "none" ];
        default = "sqlite";
        description = "Memory backend to use.";
      };

      autoSave = mkOption {
        type = types.bool;
        default = true;
        description = "Automatically save memories.";
      };

      embeddingProvider = mkOption {
        type = types.enum [ "openai" "noop" ];
        default = "noop";
        description = "Embedding provider for vector search.";
      };
    };

    # Gateway Configuration
    gateway = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable the gateway webhook server.";
      };

      port = mkOption {
        type = types.port;
        default = 8080;
        description = "Port for the gateway server.";
      };

      host = mkOption {
        type = types.str;
        default = "127.0.0.1";
        description = "Host to bind the gateway server to.";
      };

      requirePairing = mkOption {
        type = types.bool;
        default = true;
        description = "Require pairing code on first connect.";
      };

      allowPublicBind = mkOption {
        type = types.bool;
        default = false;
        description = "Allow binding to public interfaces without tunnel.";
      };
    };

    # Daemon Configuration
    daemon = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable the ZeroClaw daemon service.";
      };
    };

    # Autonomy Configuration
    autonomy = {
      level = mkOption {
        type = types.enum [ "readonly" "supervised" "full" ];
        default = "supervised";
        description = "Autonomy level for the agent.";
      };

      workspaceOnly = mkOption {
        type = types.bool;
        default = true;
        description = "Restrict operations to workspace directory.";
      };

      allowedCommands = mkOption {
        type = types.listOf types.str;
        default = [ "git" "npm" "cargo" "ls" "cat" "grep" ];
        description = "List of allowed shell commands.";
      };
    };

    # Workspace
    workspaceDir = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Workspace directory. Defaults to ~/.zeroclaw/workspace.";
    };

    # Extra configuration
    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Extra configuration to append to config.toml.";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    # Package installation
    {
      home.packages = [ cfg.package ];
    }

    # Configuration file
    {
      home.file."${cfgFile}".text = ''
        # ZeroClaw configuration - generated by home-manager
        # Do not edit manually; changes will be overwritten.

        default_provider = "${cfg.provider}"
        default_model = "${cfg.model}"
        default_temperature = ${toString cfg.temperature}
        ${optionalString (cfg.workspaceDir != null) ''workspace_dir = "${cfg.workspaceDir}"''}

        [memory]
        backend = "${cfg.memory.backend}"
        auto_save = ${boolToString cfg.memory.autoSave}
        embedding_provider = "${cfg.memory.embeddingProvider}"

        [gateway]
        port = ${toString cfg.gateway.port}
        host = "${cfg.gateway.host}"
        require_pairing = ${boolToString cfg.gateway.requirePairing}
        allow_public_bind = ${boolToString cfg.gateway.allowPublicBind}

        [autonomy]
        level = "${cfg.autonomy.level}"
        workspace_only = ${boolToString cfg.autonomy.workspaceOnly}
        allowed_commands = ${builtins.toJSON cfg.autonomy.allowedCommands}

        [runtime]
        kind = "native"

        [secrets]
        encrypt = true

        ${cfg.extraConfig}
      '';
    }

    # API key handling
    (mkIf (cfg.apiKeyFile != null) {
      home.file."${cfgFile}".text = lib.mkAfter ''
        # API key loaded from file at runtime
      '';
    })

    # Gateway systemd service (Linux only)
    (mkIf (cfg.gateway.enable && pkgs.stdenv.isLinux) {
      systemd.user.services.zeroclaw-gateway = {
        Unit = {
          Description = "ZeroClaw Gateway Webhook Server";
          After = [ "network.target" ];
        };

        Service = {
          Type = "simple";
          ExecStart = "${cfg.package}/bin/zeroclaw gateway --port ${toString cfg.gateway.port} --host ${cfg.gateway.host}";
          Restart = "on-failure";
          RestartSec = "5s";
        };

        Install = {
          WantedBy = [ "default.target" ];
        };
      };
    })

    # Daemon systemd service (Linux only)
    (mkIf (cfg.daemon.enable && pkgs.stdenv.isLinux) {
      systemd.user.services.zeroclaw-daemon = {
        Unit = {
          Description = "ZeroClaw Autonomous Daemon";
          After = [ "network.target" ];
        };

        Service = {
          Type = "simple";
          ExecStart = "${cfg.package}/bin/zeroclaw daemon";
          Restart = "on-failure";
          RestartSec = "5s";
        };

        Install = {
          WantedBy = [ "default.target" ];
        };
      };
    })
  ]);
}